version: '3.3'
services:
   ampache:
     container_name: ampache
     image: ampache/ampache
     restart: unless-stopped
     links:
      - mysql
     ports:
       - 3444:80
     volumes:
       - ./data/to/media:/media:ro
   mysql:
     container_name: mysql
     image: mysql:8.0
     restart: unless-stopped
     volumes:
      - ./data:/var/lib/mysql
     environment:
      - MYSQL_ROOT_PASSWORD:12345
